<?xml version="1.0"?>
<package format="3">
  <name>rk3576_footbath_navigation</name>
  <version>0.1.0</version>
  <description>RK3576 足浴桶 Nav2、AMCL、地图和 RViz 配置。</description>
  <maintainer email="sky@example.com">sky</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>nav2_costmap_2d</exec_depend>
  <exec_depend>rk3576_footbath_costmap</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
